# Generated by Django 3.2.5 on 2022-01-26 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypageapp', '0002_alter_pet_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='user',
            new_name='user_id',
        ),
    ]
