# Generated by Django 3.2.5 on 2022-01-26 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypageapp', '0003_rename_user_pet_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='user_id',
            new_name='user',
        ),
    ]
